export const CHANGE_VOLUME = 'CHANGE_VOLUME';

export const SET_GAME_STATE_ACTIVE = 'SET_GAME_STATE_ACTIVE';
export const SET_GAME_STATE_INACTIVE = 'SET_GAME_STATE_INACTIVE';

export const CARD_VALUE_SELECTED = 'CARD_VALUE_SELECTED';
